services:

  postgres:
    image: postgres:15
    container_name: nz_transport_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: transport_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-db:
    image: postgres:15
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5434:5432"

  airflow-init:
    image: apache/airflow:2.9.1
    container_name: airflow_init
    depends_on:
      - airflow-db
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./etl:/opt/airflow/etl
      - ./config:/opt/airflow/config
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create
        --username admin
        --firstname Savi
        --lastname Data
        --role Admin
        --email admin@example.com
        --password admin
      "

  airflow-webserver:
    image: apache/airflow:2.9.1
    container_name: airflow_webserver
    depends_on:
      - airflow-db
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: my_super_secret_key
      DB_HOST: nz_transport_postgres
      DB_PORT: 5432
      DB_NAME: transport_db
      DB_USER: admin
      DB_PASSWORD: admin123
    volumes:
      - ./dags:/opt/airflow/dags
      - ./etl:/opt/airflow/etl
      - ./config:/opt/airflow/config
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.9.1
    container_name: airflow_scheduler
    depends_on:
      - airflow-db
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: my_super_secret_key
      DB_HOST: nz_transport_postgres
      DB_PORT: 5432
      DB_NAME: transport_db
      DB_USER: admin
      DB_PASSWORD: admin123
    volumes:
      - ./dags:/opt/airflow/dags
      - ./etl:/opt/airflow/etl
      - ./config:/opt/airflow/config
    command: scheduler

volumes:
  postgres_data:
